### ISSUE TITLE
Transforming from command line doesn't work

### ISSUE THREAD

**Issue by nathanboktae** [pluma0/string-to-jsify#1]
With browserify@4.1.5

```
~/temp/b  
 1:10PM ᐅ ./node_modules/.bin/browserify -t string-to-jsify wat.js                   
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
<blink>wat</blink>

},{}],2:[function(require,module,exports){
var partial = require('./partial.html');

},{"./partial.html":1}]},{},[2])%                                                                                      
```

**Comment by pluma** [comment]
Have you tried using the JS API? I wouldn't be surprised if this is a compatibility problem with browserify 4. I'm planning to move a project in which I'm using this transform from browserify 3 to browserify 4 in the near future, so if this is a compatibility issue I'll run into this anyway.

**Comment by nathanboktae** [comment]
No, as that's not my use case. I'm using (rfile)[https://github.com/ForbesLindesay/rfileify] now since it does support that case.

**Comment by pluma** [comment]
I have added a test case for the CLI and updated the dependencies. I was unable to reproduce the problem, so I hope updating the dependencies fixed it.

Could you give it another try (with 0.4.0) to see whether the issue has been fixed? If not, it would be helpful if you could tell me how your setup differed from what's in the example folder.
